"""Contenido de la página de demos de IA aplicada a QA.

IMPORTANTE (regla del proyecto, ver CLAUDE.md "Enfoque de IA del portafolio"):
estas respuestas son EJEMPLOS REALES PREGENERADOS, no salidas en vivo. Se
generaron con el modelo indicado en MODEL, en una sesión de Claude Code, y la
página lo dice siempre. Nunca presentarlos como "en vivo".

Los ejemplos de tests de API (`apitests`) se ejecutan contra la API real en
app/tests/test_demos.py::test_api_examples_run_against_real_api (marcada para
correr solo a mano, con red) antes de publicarlos.
"""

# Quién generó estas respuestas. Si cambia el modelo, cambia aquí y se refleja en el sitio.
MODEL = {
    "provider": "Claude",
    "name": "Claude Sonnet 5.5",
    "date": "2026-10-07",
}

DEMO_ORDER = ("testcases", "bugs", "apitests")

UI = {
    "es": {
        "title": "Demos de IA aplicada a QA",
        "crumb": "demos",
        "eyebrow": "Demos IA",
        "h1": "IA aplicada a QA, con ejemplos reales",
        "lead": "Tres tareas de QA donde uso IA a diario: diseñar casos de prueba, diagnosticar fallos y escribir tests de API. Elige un ejemplo y mira qué entra y qué sale.",
        "notice_title": "Ejemplos reales, no en vivo",
        "notice_text": "Cada respuesta de esta página la generó de verdad {provider} ({model}) en una sesión de Claude Code, el {date}. No se genera en este momento a partir de lo que tú escribas: no hay un cuadro de entrada libre. Estoy evaluando proveedores de IA para un modo en vivo, y cuando exista cada demo indicará qué modelo lo genera.",
        "generated_with": "Generado con {model}",
        "input_label": "Entrada",
        "output_label": "Salida",
        "real_case": "Caso real de este proyecto",
        "executed": "Ejecutado contra la API real antes de publicarlo",
        "questions_title": "Preguntas que la historia deja sin responder",
        "steps": "Pasos",
        "expected": "Resultado esperado",
        "summary": "Resumen",
        "cause": "Causa probable",
        "evidence": "Evidencia en la traza",
        "fix": "Cómo corregirlo",
        "verify": "Cómo confirmarlo",
        "severity": "Severidad",
        "notes": "Notas",
        "back": "Volver al inicio",
        "demos": {
            "testcases": {
                "name": "Generador de casos de prueba",
                "what": "Entra una historia de usuario con sus criterios de aceptación. Salen casos de prueba con valores límite y casos negativos, más las preguntas que la historia deja abiertas.",
            },
            "bugs": {
                "name": "Analizador de bugs",
                "what": "Entra una traza de error con un poco de contexto. Sale un diagnóstico: qué pasó, causa probable, evidencia en la traza, cómo corregirlo y cómo confirmarlo.",
            },
            "apitests": {
                "name": "Generador de tests de API",
                "what": "Entra la especificación de un endpoint. Sale una suite pytest + requests, con los datos únicos por test y los defectos conocidos de la API marcados como tales.",
            },
        },
    },
    "en": {
        "title": "AI demos applied to QA",
        "crumb": "demos",
        "eyebrow": "AI demos",
        "h1": "AI applied to QA, with real examples",
        "lead": "Three QA tasks where I use AI every day: designing test cases, diagnosing failures and writing API tests. Pick an example and see what goes in and what comes out.",
        "notice_title": "Real examples, not live",
        "notice_text": "Every answer on this page was genuinely generated by {provider} ({model}) in a Claude Code session on {date}. Nothing is generated right now from what you type: there is no free-text input box. I am evaluating AI providers for a live mode, and once it exists each demo will state which model generates it.",
        "generated_with": "Generated with {model}",
        "input_label": "Input",
        "output_label": "Output",
        "real_case": "Real case from this project",
        "executed": "Run against the real API before publishing",
        "questions_title": "Questions the story leaves unanswered",
        "steps": "Steps",
        "expected": "Expected result",
        "summary": "Summary",
        "cause": "Probable cause",
        "evidence": "Evidence in the trace",
        "fix": "How to fix it",
        "verify": "How to confirm it",
        "severity": "Severity",
        "notes": "Notes",
        "back": "Back to home",
        "demos": {
            "testcases": {
                "name": "Test case generator",
                "what": "In: a user story with its acceptance criteria. Out: test cases with boundary values and negative cases, plus the questions the story leaves open.",
            },
            "bugs": {
                "name": "Bug analyzer",
                "what": "In: an error trace with a little context. Out: a diagnosis: what happened, probable cause, evidence in the trace, how to fix it and how to confirm it.",
            },
            "apitests": {
                "name": "API test generator",
                "what": "In: the spec of an endpoint. Out: a pytest + requests suite, with unique data per test and the API's known defects marked as such.",
            },
        },
    },
}

# ---------------------------------------------------------------- código de los tests de API
# Un solo código para ES y EN (comentarios en inglés, como es convención). Es EXACTAMENTE
# lo que se muestra y lo que se ejecutó contra la API real.

CODE_AUTH = '''import requests

BASE_URL = "https://restful-booker.herokuapp.com"


def test_auth_valid_credentials_returns_token():
    response = requests.post(
        f"{BASE_URL}/auth",
        json={"username": "admin", "password": "password123"},
        timeout=30,
    )
    assert response.status_code == 200
    token = response.json()["token"]
    assert isinstance(token, str) and token


def test_auth_invalid_credentials_returns_reason_not_token():
    # The API answers 200 even for bad credentials, so the body decides, not the status code.
    response = requests.post(
        f"{BASE_URL}/auth",
        json={"username": "admin", "password": "wrong-password"},
        timeout=30,
    )
    assert response.status_code == 200
    body = response.json()
    assert "token" not in body
    assert body["reason"] == "Bad credentials"


def test_auth_missing_password_returns_reason_not_token():
    response = requests.post(f"{BASE_URL}/auth", json={"username": "admin"}, timeout=30)
    body = response.json()
    assert "token" not in body
    assert body["reason"] == "Bad credentials"
'''

CODE_BOOKING = '''import uuid

import pytest
import requests

BASE_URL = "https://restful-booker.herokuapp.com"
HEADERS = {"Content-Type": "application/json", "Accept": "application/json"}


def new_booking():
    # Every test builds its own data, with a unique component.
    return {
        "firstname": "Ana",
        "lastname": f"Prueba-{uuid.uuid4().hex[:8]}",
        "totalprice": 150,
        "depositpaid": True,
        "bookingdates": {"checkin": "2026-11-01", "checkout": "2026-11-05"},
        "additionalneeds": "Breakfast",
    }


def create(payload):
    return requests.post(f"{BASE_URL}/booking", json=payload, headers=HEADERS, timeout=30)


def test_create_booking_valid_payload_returns_id_and_echoes_data():
    payload = new_booking()
    response = create(payload)
    assert response.status_code == 200
    body = response.json()
    assert isinstance(body["bookingid"], int)
    assert body["booking"] == payload


def test_create_booking_can_be_read_back_with_same_data():
    payload = new_booking()
    booking_id = create(payload).json()["bookingid"]
    response = requests.get(f"{BASE_URL}/booking/{booking_id}", headers=HEADERS, timeout=30)
    assert response.status_code == 200
    assert response.json() == payload


def test_create_booking_missing_firstname_returns_server_error():
    # Verified real behaviour: the API answers 500 (not 400) to an incomplete payload.
    payload = new_booking()
    del payload["firstname"]
    assert create(payload).status_code == 500


def test_get_booking_unknown_id_returns_404():
    response = requests.get(f"{BASE_URL}/booking/99999999", headers=HEADERS, timeout=30)
    assert response.status_code == 404


@pytest.mark.xfail(strict=True, reason="The API accepts a non-numeric price and stores it as null")
def test_create_booking_non_numeric_price_is_rejected():
    payload = new_booking()
    payload["totalprice"] = "a lot"
    assert create(payload).status_code >= 400
'''

# ---------------------------------------------------------------- ejemplos
EXAMPLES = {
    "testcases": {
        "es": [
            {
                "id": "reserva",
                "title": "Reserva de una habitación",
                "input": (
                    "Historia de usuario:\n"
                    "Como visitante del hotel quiero reservar una habitación eligiendo fechas de entrada y salida "
                    "y dejando mis datos de contacto, para confirmar mi estancia.\n\n"
                    "Criterios de aceptación:\n"
                    "- Las fechas de entrada y salida son obligatorias y la salida debe ser posterior a la entrada.\n"
                    "- El nombre y el apellido son obligatorios.\n"
                    "- El correo debe tener un formato válido.\n"
                    "- El teléfono debe tener entre 11 y 21 caracteres.\n"
                    "- Al confirmar, se muestra un mensaje de reserva confirmada con las fechas elegidas."
                ),
                "output": {
                    "cases": [
                        {"id": "TC-01", "type": "Funcional", "title": "Reserva exitosa con datos válidos",
                         "steps": ["Elegir una fecha de entrada y una de salida posterior", "Completar nombre, apellido, correo válido y un teléfono de 11 caracteres", "Confirmar la reserva"],
                         "expected": "Se muestra el mensaje de reserva confirmada con las fechas elegidas."},
                        {"id": "TC-02", "type": "Valor límite", "title": "Teléfono de 10 caracteres (uno por debajo del mínimo)",
                         "steps": ["Completar el formulario con datos válidos y un teléfono de exactamente 10 caracteres", "Confirmar la reserva"],
                         "expected": "Se muestra un error de longitud en el teléfono y la reserva no se crea."},
                        {"id": "TC-03", "type": "Valor límite", "title": "Teléfono de 11 y de 21 caracteres (los dos límites válidos)",
                         "steps": ["Reservar con un teléfono de exactamente 11 caracteres", "Repetir la reserva con uno de exactamente 21"],
                         "expected": "Ambas reservas se aceptan."},
                        {"id": "TC-04", "type": "Valor límite", "title": "Teléfono de 22 caracteres (uno por encima del máximo)",
                         "steps": ["Completar el formulario con datos válidos y un teléfono de 22 caracteres", "Confirmar la reserva"],
                         "expected": "Se muestra un error de longitud y la reserva no se crea."},
                        {"id": "TC-05", "type": "Negativo", "title": "Fecha de salida anterior a la de entrada",
                         "steps": ["Elegir una fecha de salida anterior a la de entrada", "Completar el resto con datos válidos", "Confirmar la reserva"],
                         "expected": "No se permite la reserva y se indica que la salida debe ser posterior a la entrada."},
                        {"id": "TC-06", "type": "Negativo", "title": "Correo con formato inválido",
                         "steps": ["Escribir un correo sin arroba", "Completar el resto con datos válidos", "Confirmar la reserva"],
                         "expected": "Se muestra un error de formato en el correo y la reserva no se crea."},
                    ],
                    "questions": [
                        "¿Qué pasa si las fechas elegidas ya están reservadas? La historia no lo define.",
                        "¿Hay un máximo de noches por reserva?",
                        "¿El teléfono acepta símbolos como + o espacios, o solo dígitos?",
                        "¿Se puede elegir una fecha de entrada en el pasado?",
                    ],
                },
            },
            {
                "id": "login",
                "title": "Inicio de sesión de administrador",
                "input": (
                    "Historia de usuario:\n"
                    "Como administrador quiero iniciar sesión con mi usuario y contraseña, para gestionar las habitaciones del hotel.\n\n"
                    "Criterios de aceptación:\n"
                    "- Con credenciales válidas se muestra el menú de administración (Rooms, Report).\n"
                    "- Con credenciales inválidas se muestra un mensaje de error y el administrador sigue en el formulario de login.\n"
                    "- Sin haber iniciado sesión no se puede ver el panel de habitaciones.\n"
                    "- Al cerrar sesión se vuelve a la portada y el menú de administración desaparece."
                ),
                "output": {
                    "cases": [
                        {"id": "TC-01", "type": "Funcional", "title": "Inicio de sesión con credenciales válidas",
                         "steps": ["Abrir el login de administrador", "Escribir usuario y contraseña válidos", "Pulsar Login"],
                         "expected": "Se muestra el menú de administración con Rooms y Report."},
                        {"id": "TC-02", "type": "Negativo", "title": "Contraseña incorrecta",
                         "steps": ["Escribir un usuario válido y una contraseña incorrecta", "Pulsar Login", "Esperar a que aparezca el mensaje de error"],
                         "expected": "Aparece un mensaje de error, el formulario sigue visible y el menú de administración no aparece. Hay que esperar primero el mensaje: comprobar que algo \"no está\" se cumple al instante y no prueba que el servidor ya respondió."},
                        {"id": "TC-03", "type": "Negativo", "title": "Campos vacíos",
                         "steps": ["Dejar usuario y contraseña vacíos", "Pulsar Login"],
                         "expected": "No se inicia sesión y no aparece el menú de administración."},
                        {"id": "TC-04", "type": "Seguridad", "title": "Acceso directo al panel sin sesión",
                         "steps": ["En una sesión nueva, abrir directamente la URL del panel de habitaciones"],
                         "expected": "No se muestran datos de habitaciones."},
                        {"id": "TC-05", "type": "Funcional", "title": "Cerrar sesión",
                         "steps": ["Iniciar sesión con credenciales válidas", "Pulsar Logout"],
                         "expected": "Se vuelve a la portada y el menú de administración desaparece."},
                    ],
                    "questions": [
                        "¿Hay bloqueo tras varios intentos fallidos? La historia no lo menciona.",
                        "¿El mensaje de error revela si el usuario existe? Conviene un mensaje genérico.",
                        "¿La sesión caduca por inactividad?",
                    ],
                },
            },
        ],
        "en": [
            {
                "id": "reserva",
                "title": "Booking a room",
                "input": (
                    "User story:\n"
                    "As a hotel visitor I want to book a room by choosing check-in and check-out dates "
                    "and leaving my contact details, so that I can confirm my stay.\n\n"
                    "Acceptance criteria:\n"
                    "- Check-in and check-out dates are required and check-out must be after check-in.\n"
                    "- First and last name are required.\n"
                    "- The email must have a valid format.\n"
                    "- The phone must be between 11 and 21 characters long.\n"
                    "- On confirming, a booking-confirmed message is shown with the chosen dates."
                ),
                "output": {
                    "cases": [
                        {"id": "TC-01", "type": "Functional", "title": "Successful booking with valid data",
                         "steps": ["Pick a check-in date and a later check-out date", "Fill in first name, last name, a valid email and an 11-character phone", "Confirm the booking"],
                         "expected": "The booking-confirmed message is shown with the chosen dates."},
                        {"id": "TC-02", "type": "Boundary value", "title": "10-character phone (one below the minimum)",
                         "steps": ["Fill the form with valid data and a phone of exactly 10 characters", "Confirm the booking"],
                         "expected": "A length error is shown on the phone field and the booking is not created."},
                        {"id": "TC-03", "type": "Boundary value", "title": "11- and 21-character phones (both valid limits)",
                         "steps": ["Book with a phone of exactly 11 characters", "Repeat the booking with one of exactly 21"],
                         "expected": "Both bookings are accepted."},
                        {"id": "TC-04", "type": "Boundary value", "title": "22-character phone (one above the maximum)",
                         "steps": ["Fill the form with valid data and a 22-character phone", "Confirm the booking"],
                         "expected": "A length error is shown and the booking is not created."},
                        {"id": "TC-05", "type": "Negative", "title": "Check-out date before check-in",
                         "steps": ["Pick a check-out date earlier than the check-in date", "Fill the rest with valid data", "Confirm the booking"],
                         "expected": "The booking is not allowed and the message says check-out must be after check-in."},
                        {"id": "TC-06", "type": "Negative", "title": "Email with an invalid format",
                         "steps": ["Type an email without an at-sign", "Fill the rest with valid data", "Confirm the booking"],
                         "expected": "A format error is shown on the email field and the booking is not created."},
                    ],
                    "questions": [
                        "What happens if the chosen dates are already booked? The story does not say.",
                        "Is there a maximum number of nights per booking?",
                        "Does the phone accept symbols such as + or spaces, or digits only?",
                        "Can the check-in date be in the past?",
                    ],
                },
            },
            {
                "id": "login",
                "title": "Administrator login",
                "input": (
                    "User story:\n"
                    "As an administrator I want to log in with my username and password, so that I can manage the hotel rooms.\n\n"
                    "Acceptance criteria:\n"
                    "- With valid credentials the admin menu is shown (Rooms, Report).\n"
                    "- With invalid credentials an error message is shown and the administrator stays on the login form.\n"
                    "- Without logging in, the rooms panel cannot be seen.\n"
                    "- On logging out, the user returns to the front page and the admin menu disappears."
                ),
                "output": {
                    "cases": [
                        {"id": "TC-01", "type": "Functional", "title": "Login with valid credentials",
                         "steps": ["Open the admin login", "Type a valid username and password", "Click Login"],
                         "expected": "The admin menu with Rooms and Report is shown."},
                        {"id": "TC-02", "type": "Negative", "title": "Wrong password",
                         "steps": ["Type a valid username and a wrong password", "Click Login", "Wait for the error message to appear"],
                         "expected": "An error message appears, the form is still visible and the admin menu does not appear. Wait for the message first: checking that something is \"not there\" passes instantly and does not prove the server has answered."},
                        {"id": "TC-03", "type": "Negative", "title": "Empty fields",
                         "steps": ["Leave username and password empty", "Click Login"],
                         "expected": "The user is not logged in and the admin menu does not appear."},
                        {"id": "TC-04", "type": "Security", "title": "Direct access to the panel without a session",
                         "steps": ["In a fresh session, open the rooms panel URL directly"],
                         "expected": "No room data is shown."},
                        {"id": "TC-05", "type": "Functional", "title": "Log out",
                         "steps": ["Log in with valid credentials", "Click Logout"],
                         "expected": "The user returns to the front page and the admin menu disappears."},
                    ],
                    "questions": [
                        "Is there a lockout after several failed attempts? The story does not mention it.",
                        "Does the error message reveal whether the user exists? A generic message is preferable.",
                        "Does the session expire after inactivity?",
                    ],
                },
            },
        ],
    },
    "bugs": {
        "es": [
            {
                "id": "locator",
                "title": "Playwright: no aparece el enlace Rooms",
                "real_case": True,
                "input": (
                    "Contexto: test de Playwright (pytest) contra la app de práctica. "
                    "Test: test_admin_login_wrong_password_shows_rooms_menu_probe\n\n"
                    "E       AssertionError: Locator expected to be visible\n"
                    "E       Actual value: None\n"
                    "E       Error: element(s) not found\n"
                    "E       Call log:\n"
                    "E         - Expect \"to_be_visible\" with timeout 5000ms\n"
                    "E         - waiting for get_by_role(\"link\", name=\"Rooms\")\n\n"
                    "tests/admin/test_admin_negative.py:18: AssertionError"
                ),
                "output": {
                    "summary": "El test esperaba ver el enlace «Rooms» (menú de administrador) tras iniciar sesión, pero el enlace no apareció durante los 5 segundos de espera.",
                    "cause": "Lo más probable es que el error esté en el test y no en la aplicación: el nombre del test dice que el login se hizo con una contraseña incorrecta, y con credenciales inválidas el menú de administrador no debería aparecer. El locator es válido; simplemente no hay nada que encontrar.",
                    "evidence": [
                        "«element(s) not found» después de agotar el timeout completo: el elemento no existe, no es un problema de tiempo de carga.",
                        "El nombre del test se contradice a sí mismo: «wrong_password» y «shows_rooms_menu».",
                        "La traza no muestra ningún error de red ni de otro tipo: la página cargó.",
                    ],
                    "fix": [
                        "Cambiar la expectativa: con contraseña incorrecta, comprobar que el menú NO aparece y que se muestra el mensaje de error.",
                        "Si el test sí debía iniciar sesión, usar credenciales válidas.",
                        "Esperar primero el mensaje de error antes de comprobar la ausencia del menú.",
                    ],
                    "verify": [
                        "Revisar el aria snapshot del momento del fallo: debería mostrar el formulario de login con un elemento «alert».",
                        "Repetir el test con credenciales válidas: el enlace debería aparecer.",
                    ],
                    "severity": "Baja — error del test, no del producto",
                },
            },
            {
                "id": "allure",
                "title": "pytest revienta al arrancar",
                "real_case": True,
                "input": (
                    "Contexto: al ejecutar pytest en la suite de API, falla antes de correr ningún test.\n\n"
                    "Traceback (most recent call last):\n"
                    "  File \"pytest.exe\\__main__.py\", line 6, in <module>\n"
                    "  File \"allure_pytest_bdd\\plugin.py\", line 18, in pytest_addoption\n"
                    "    parser.getgroup(\"reporting\").addoption(\"--alluredir\", ...)\n"
                    "  File \"_pytest\\config\\argparsing.py\", line 357, in addoption\n"
                    "    raise ValueError(f\"option names {conflict} already added\")\n"
                    "ValueError: option names {'--alluredir'} already added"
                ),
                "output": {
                    "summary": "pytest falla mientras carga plugins, antes de ejecutar ningún test: dos plugins intentan registrar la misma opción de línea de comandos, «--alluredir».",
                    "cause": "allure-pytest y allure-pytest-bdd están instalados en el mismo entorno y ambos se cargan automáticamente. Cada uno declara «--alluredir» y pytest no admite dos opciones con el mismo nombre. No es un error del código de los tests.",
                    "evidence": [
                        "La excepción sale de «pytest_addoption» de «allure_pytest_bdd», es decir, durante el arranque.",
                        "El mensaje dice «already added»: otra pieza ya registró esa opción antes.",
                        "No aparece ningún test en la salida: pytest nunca llegó a recolectarlos.",
                    ],
                    "fix": [
                        "Desactivar uno de los dos plugins en pytest.ini con «-p no:allure_pytest_bdd» (el que esa suite no use).",
                        "Si una suite necesita ambos en momentos distintos, activarlos de uno en uno con «-p allure_pytest» o «-p allure_pytest_bdd».",
                        "Dejar la restricción escrita en la documentación para no redescubrirla.",
                    ],
                    "verify": [
                        "Listar los paquetes instalados y confirmar que están los dos plugins de Allure.",
                        "Ejecutar pytest con «-p no:allure_pytest_bdd» y comprobar que arranca.",
                    ],
                    "severity": "Media — bloquea toda la suite, pero la solución es de configuración",
                },
            },
        ],
        "en": [
            {
                "id": "locator",
                "title": "Playwright: the Rooms link never shows up",
                "real_case": True,
                "input": (
                    "Context: Playwright (pytest) test against the practice app. "
                    "Test: test_admin_login_wrong_password_shows_rooms_menu_probe\n\n"
                    "E       AssertionError: Locator expected to be visible\n"
                    "E       Actual value: None\n"
                    "E       Error: element(s) not found\n"
                    "E       Call log:\n"
                    "E         - Expect \"to_be_visible\" with timeout 5000ms\n"
                    "E         - waiting for get_by_role(\"link\", name=\"Rooms\")\n\n"
                    "tests/admin/test_admin_negative.py:18: AssertionError"
                ),
                "output": {
                    "summary": "The test expected to see the \"Rooms\" link (admin menu) after logging in, but the link did not appear within the 5-second wait.",
                    "cause": "Most likely the test is wrong, not the application: the test name says the login used a wrong password, and with invalid credentials the admin menu should not appear. The locator is valid; there is simply nothing to find.",
                    "evidence": [
                        "\"element(s) not found\" after exhausting the full timeout: the element does not exist, so this is not a slow-load problem.",
                        "The test name contradicts itself: \"wrong_password\" and \"shows_rooms_menu\".",
                        "The trace shows no network or other error: the page loaded.",
                    ],
                    "fix": [
                        "Change the expectation: with a wrong password, check that the menu does NOT appear and that the error message is shown.",
                        "If the test was meant to log in, use valid credentials.",
                        "Wait for the error message first, before checking that the menu is absent.",
                    ],
                    "verify": [
                        "Check the aria snapshot taken at the time of the failure: it should show the login form with an \"alert\" element.",
                        "Re-run the test with valid credentials: the link should appear.",
                    ],
                    "severity": "Low — a test error, not a product error",
                },
            },
            {
                "id": "allure",
                "title": "pytest blows up on startup",
                "real_case": True,
                "input": (
                    "Context: running pytest on the API suite fails before any test runs.\n\n"
                    "Traceback (most recent call last):\n"
                    "  File \"pytest.exe\\__main__.py\", line 6, in <module>\n"
                    "  File \"allure_pytest_bdd\\plugin.py\", line 18, in pytest_addoption\n"
                    "    parser.getgroup(\"reporting\").addoption(\"--alluredir\", ...)\n"
                    "  File \"_pytest\\config\\argparsing.py\", line 357, in addoption\n"
                    "    raise ValueError(f\"option names {conflict} already added\")\n"
                    "ValueError: option names {'--alluredir'} already added"
                ),
                "output": {
                    "summary": "pytest fails while loading plugins, before running any test: two plugins try to register the same command-line option, \"--alluredir\".",
                    "cause": "allure-pytest and allure-pytest-bdd are installed in the same environment and both load automatically. Each declares \"--alluredir\" and pytest does not allow two options with the same name. This is not a bug in the test code.",
                    "evidence": [
                        "The exception comes from \"pytest_addoption\" in \"allure_pytest_bdd\", that is, during startup.",
                        "The message says \"already added\": something else registered that option first.",
                        "No test appears in the output: pytest never got to collect them.",
                    ],
                    "fix": [
                        "Disable one of the two plugins in pytest.ini with \"-p no:allure_pytest_bdd\" (the one that suite does not use).",
                        "If a suite needs both at different times, enable them one at a time with \"-p allure_pytest\" or \"-p allure_pytest_bdd\".",
                        "Write the restriction down in the docs so it is not rediscovered.",
                    ],
                    "verify": [
                        "List the installed packages and confirm both Allure plugins are there.",
                        "Run pytest with \"-p no:allure_pytest_bdd\" and check that it starts.",
                    ],
                    "severity": "Medium — it blocks the whole suite, but the fix is configuration",
                },
            },
        ],
    },
    "apitests": {
        "es": [
            {
                "id": "auth",
                "title": "Autenticación (POST /auth)",
                "input": (
                    "POST https://restful-booker.herokuapp.com/auth\n"
                    "Content-Type: application/json\n"
                    "Body: {\"username\": \"admin\", \"password\": \"password123\"}\n\n"
                    "Credenciales válidas:   200  {\"token\": \"<string>\"}\n"
                    "Credenciales inválidas: 200  {\"reason\": \"Bad credentials\"}"
                ),
                "output": {
                    "code": CODE_AUTH,
                    "notes": [
                        "La especificación ya avisa de algo poco habitual: las credenciales inválidas responden 200, no 401. Por eso los tests inspeccionan el cuerpo y no confían solo en el código de estado.",
                        "Se comprobó también el caso de contraseña ausente, que la especificación no menciona: responde igual que una contraseña incorrecta.",
                    ],
                },
                "run": "3 passed",
            },
            {
                "id": "booking",
                "title": "Crear una reserva (POST /booking)",
                "input": (
                    "POST https://restful-booker.herokuapp.com/booking\n"
                    "Content-Type: application/json\n"
                    "Accept: application/json\n"
                    "Body: {\"firstname\": string, \"lastname\": string, \"totalprice\": number,\n"
                    "       \"depositpaid\": boolean,\n"
                    "       \"bookingdates\": {\"checkin\": \"YYYY-MM-DD\", \"checkout\": \"YYYY-MM-DD\"},\n"
                    "       \"additionalneeds\": string (opcional)}\n\n"
                    "Respuesta: 200  {\"bookingid\": number, \"booking\": {...}}\n"
                    "GET /booking/{id} devuelve la reserva creada."
                ),
                "output": {
                    "code": CODE_BOOKING,
                    "notes": [
                        "Cada test arma su propio dato con un componente único (uuid), porque la API es compartida y un valor fijo puede chocar con el de otra ejecución.",
                        "Un payload sin «firstname» responde 500, no 400: es el comportamiento real y el test lo documenta tal cual.",
                        "El último test documenta un defecto real como «xfail(strict=True)»: hoy la API acepta un precio no numérico y lo guarda como null. Si algún día lo corrigen, el test pasará y avisará con un fallo para retirar la marca.",
                    ],
                },
                "run": "4 passed, 1 xfailed",
            },
        ],
        "en": [
            {
                "id": "auth",
                "title": "Authentication (POST /auth)",
                "input": (
                    "POST https://restful-booker.herokuapp.com/auth\n"
                    "Content-Type: application/json\n"
                    "Body: {\"username\": \"admin\", \"password\": \"password123\"}\n\n"
                    "Valid credentials:   200  {\"token\": \"<string>\"}\n"
                    "Invalid credentials: 200  {\"reason\": \"Bad credentials\"}"
                ),
                "output": {
                    "code": CODE_AUTH,
                    "notes": [
                        "The spec already flags something unusual: invalid credentials answer 200, not 401. That is why the tests inspect the body instead of trusting the status code alone.",
                        "The missing-password case, which the spec does not mention, was also checked: it answers the same as a wrong password.",
                    ],
                },
                "run": "3 passed",
            },
            {
                "id": "booking",
                "title": "Create a booking (POST /booking)",
                "input": (
                    "POST https://restful-booker.herokuapp.com/booking\n"
                    "Content-Type: application/json\n"
                    "Accept: application/json\n"
                    "Body: {\"firstname\": string, \"lastname\": string, \"totalprice\": number,\n"
                    "       \"depositpaid\": boolean,\n"
                    "       \"bookingdates\": {\"checkin\": \"YYYY-MM-DD\", \"checkout\": \"YYYY-MM-DD\"},\n"
                    "       \"additionalneeds\": string (optional)}\n\n"
                    "Response: 200  {\"bookingid\": number, \"booking\": {...}}\n"
                    "GET /booking/{id} returns the created booking."
                ),
                "output": {
                    "code": CODE_BOOKING,
                    "notes": [
                        "Each test builds its own data with a unique component (uuid), because the API is shared and a fixed value can clash with another run's.",
                        "A payload without \"firstname\" answers 500, not 400: that is the real behaviour and the test documents it as is.",
                        "The last test documents a real defect as \"xfail(strict=True)\": today the API accepts a non-numeric price and stores it as null. If it is ever fixed, the test will pass and fail loudly so the mark can be removed.",
                    ],
                },
                "run": "4 passed, 1 xfailed",
            },
        ],
    },
}
